---
kind: Service
apiVersion: v1
metadata:
  name: cars
spec:
  selector:
    app: cars
  ports:
    - port: 8080
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: cars
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cars
    spec:
      containers:
      - name: cars
        image: cars:1
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---